#Este archivo define servicios de autoridad de certificación (CA) para cada organización en la red. 
#Cada organización tiene un servicio de CA raíz y un servicio de CA TLS.
#El servicio de CA raíz se utiliza para registrar y emitir certificados para los administradores de la organización.

version: '3.7'

networks:
  basic:
services:
  root.ca.org1.acme.com:
    image: hyperledger/fabric-ca:latest
    container_name: root.ca.org1.acme.com
    ports:
      - "7054:7054"
    volumes:
      - ./crypto-config/org1.acme.com/root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    environment:
      - FABRIC_CA_SERVER_ENABLED=true
    networks:
      - basic
  tls.root.ca.org1.acme.com:
    image: hyperledger/fabric-ca:latest
    container_name: tls.root.ca.org1.acme.com
    ports:
      - "7055:7054"
    volumes:
      - ./crypto-config/org1.acme.com/tls-root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw" 
    networks:
      - basic

  root.ca.org2.acme.com:
    image: hyperledger/fabric-ca:latest
    container_name: root.ca.org2.acme.com
    ports:
      - "8054:7054"
    volumes:
      - ./crypto-config/org2.acme.com/root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    environment:
      - FABRIC_CA_SERVER_ENABLED=true
    networks:
      - basic
  tls.root.ca.org2.acme.com:
    image: hyperledger/fabric-ca:latest
    container_name: tls.root.ca.org2.acme.com
    ports:
      - "8055:7054"
    volumes:
      - ./crypto-config/org2.acme.com/tls-root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - basic
  
  root.ca.org3.acme.com:
    image: hyperledger/fabric-ca:latest
    container_name: root.ca.org3.acme.com
    ports:
      - "9054:7054"
    volumes:
      - ./crypto-config/org3.acme.com/root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    environment:
      - FABRIC_CA_SERVER_ENABLED=true
    networks:
      - basic
  tls.root.ca.org3.acme.com:
    image: hyperledger/fabric-ca:latest
    container_name: tls.root.ca.org3.acme.com
    ports:
      - "9055:7054"
    volumes:
      - ./crypto-config/org3.acme.com/tls-root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - basic
      
